project:
  type: website
  output-dir: docs

website:
  title: "Acosta Lab"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: "Home"
      - href: research.qmd
        text: "Research"
      - href: publications.qmd
        text: "Publications"
      - href: software.qmd
        text: "Software"
      - href: resources.qmd
        text: "Resources"
    right:
      - icon: github
        href: https://github.com/AcostaLab

format:
  html:
    theme: sandstone
    css: styles.css
