project:
  type: website
  output-dir: docs

website:
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"
      - href: publications.qmd
        text: "Publications"
      - href: software.qmd
        text: "Software"
    right:
      - icon: github
        href: https://github.com/AcostaLab

format:
  html:
    theme: sandstone
    css: styles.css
    smooth-scroll: true
