project:
  type: website
  output-dir: docs

website:
  title: "Acosta Lab"
  navbar:
    background: primary
    search: true
    left:
      - href: home.qmd
        text: "Home"
      - research.qmd
      - href: publications.qmd
        text: "Publications"
      - software.qmd
      - resources.qmd
    right:
      - icon: github
        href: https://github.com/AcostaLab

format:
  html:
    theme: sandstone
    css: styles.css
