## 2026
Mavlonazarova S, **Acosta K**, Abzalimov R, Satorov S, and Dushenkov V. (2026). Untargeted metabolomics reveals organ-specific and extraction-dependent metabolite profiles in endemic Tajik species *Ferula violacea* Korovin. *Plant Direct*, 10(3):e70123. [doi:10.1002/pld3.70123](https://doi.org/10.1002/pld3.70123)

Cho E, **Acosta K**, Henkin J, Abzalimov R, and Raskin I. (2026). Synergistic antifungal effects of botanical extracts against *Candida albicans*. *PLOS ONE*, 21(1):e0340665. [doi:10.1371/journal.pone.0340665](https://doi.org/10.1371/journal.pone.0340665)

## 2025
Kaz A, Thirunavukkarasu K, Almosd L, Cho E, Henkin J, **Acosta K**, Abzalimov R, and Raskin I. (2025). Potent surface antimicrobial activity of hydrolyzable tannins from Aleppo oak galls. *Scientific Reports*, 16:3088. [doi:10.1038/s41598-025-33013-7](https://doi.org/10.1038/s41598-025-33013-7)

Ernst E, Abramson B, **Acosta K**, Hoang PTN, Mateo-Elizalde C, Schubert V, Pasaribu B, Albert PS, Hartwick N, Colt K, Aylward A, Ramu U, Birchler JA, Schubert I, Lam E, Michael TP, and Martienssen RA. (2025). Duckweed genomes and epigenomes underlie triploid hybridization and clonal reproduction. *Current Biology*, 35(8):1828-1847. [doi:10.1016/j.cub.2025.03.013](https://doi.org/10.1016/j.cub.2025.03.013)

## 2024
**Acosta K**, Sree KS, Okamoto N, Koseki K, Sorrels S, Jahreis G, Watanabe F, Appenroth KJ, and Lam E. (2024). Source of vitamin B12 in plants of the Lemnaceae family and its production by duckweed-associated bacteria. *Journal of Food Composition and Analysis*, 135:106603. [doi:10.1016/j.jfca.2024.106603](https://doi.org/10.1016/j.jfca.2024.106603)

## 2023
Pasaribu B, **Acosta K**, Aylward A, Liang Y, Abramson BW, Colt K, Hartwick NT, Shanklin J, Michael TP, and Lam E. (2023). Genomics of turions from the Greater Duckweed reveal its pathways for dormancy and re-emergence strategy. *New Phytologist*, 239(1):116-131. [doi:10.1111/nph.18941](https://doi.org/10.1111/nph.18941)

**Acosta K**, Sorrels S, Chrisler W, Huang W, Gilbert S, Brinkman T, Michael TP, Lebeis SL, and Lam E. (2023). Optimization of molecular methods for detecting duckweed-associated bacteria. *Plants*, 12(4):872. [doi:10.3390/plants12040872](https://doi.org/10.3390/plants12040872)

## 2022
Gilbert S, Poulev A, Chrisler W, **Acosta K**, Orr G, Lebeis S, and Lam E. (2022). Auxin-producing bacteria from duckweeds have different colonization patterns and effects on plant morphology. *Plants*, 11(6):721. [doi:10.3390/plants11060721](https://doi.org/10.3390/plants11060721)

## 2021
**Acosta K**, Appenroth KJ, Borisjuk L, Edelman M, Heinig U, Jansen MAK, Oyama T, Pasaribu B, Schubert I, Sorrels S, Sree KS, Xu S, Michael TP, and Lam E. (2021). Return of the Lemnaceae: duckweed as a model plant system in the genomics and postgenomics era. *The Plant Cell*, 33(10):3207-3234. [doi:10.1093/plcell/koab189](https://doi.org/10.1093/plcell/koab189)

## 2020
Huang W, Gilbert S, Poulev A, **Acosta K**, Lebeis S, Long C, and Lam E. (2020). Host-specific and tissue-dependent orchestration of microbiome community structure in traditional rice paddy ecosystems. *Plant and Soil*, 452(1):379-395. [doi:10.1007/s11104-020-04568-3](https://doi.org/10.1007/s11104-020-04568-3)

**Acosta K**, Xu J, Gilbert S, Denison E, Brinkman T, Lebeis S, and Lam E. (2020). Duckweed hosts a taxonomically similar bacterial assemblage as the terrestrial leaf microbiome. *PLOS ONE*, 15(2):e0228560. [doi:10.1371/journal.pone.0228560](https://doi.org/10.1371/journal.pone.0228560)

## 2018
Gilbert S, Xu J, **Acosta K**, Poulev A, Lebeis S, and Lam E. (2018). Bacterial production of indole related compounds reveals their role in association between duckweeds and endophytes. *Frontiers in Chemistry*, 6:265. [doi:10.3389/fchem.2018.00265](https://doi.org/10.3389/fchem.2018.00265)

## 2017
Michael TP, Bryant D, Gutierrez R, Borisjuk N, Chu P, Zhang H, Xia J, Zhou J, Peng H, El Baidouri M, Ten Hallers B, Hastie AR, Liang T, **Acosta K**, Gilbert S, McEntee C, Jackson SA, Mockler TC, Zhang W, and Lam E. (2017). Comprehensive definition of genome features in *Spirodela polyrhiza* by high-depth physical mapping and short-read DNA sequencing strategies. *The Plant Journal*, 89(3):617-635. [doi:10.1111/tpj.13400](https://doi.org/10.1111/tpj.13400)

## 2015
Borisjuk N, Chu P, Gutierrez R, Zhang H, **Acosta K**, Friesen N, Sree KS, Garcia C, Appenroth KJ, and Lam E. (2015). Assessment, validation and deployment strategy of a two-barcode protocol for facile genotyping of duckweed species. *Plant Biology*, 17(Suppl 1):42-49. [doi:10.1111/plb.12229](https://doi.org/10.1111/plb.12229)
